# System
gpu_num: 0
seed: 42
debug: False
verbose: False

# Train / val
val_size: 0.2

# Data Loader
input_width: 512
input_height: 256
scaler: normalize
num_workers: 4
shuffle: True
drop_last: False

# Model
architecture: DeepLabV3Plus
encoder: timm-efficientnet-b0 #timm-regnety_016
encoder_weight: imagenet #noisy-student
depth: 5
n_classes: 4
activation: null

# Trainer
n_epochs: 100
batch_size: 16
loss: 
  name: FocalLoss2d #MeanCCELoss #GDLoss 
  args:
    weight: [1, 1, 1, 1]
metrics: 
  - miou
  - iou1
  - iou2
  - iou3
earlystopping_target: val_miou
earlystopping_patience: 10
optimizer:
  name: AdamW
  args:
    lr: 5.0e-04
    weight_decay: 5.0e-02
scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 100
    eta_min: 0

# Logging
plot:
  - loss
  - miou
  - iou1
  - iou2
  - iou3
